### ISSUE TITLE
Add maintainer by RTD username yields `HTTP ERROR 405`

### ISSUE THREAD

**Issue by stevepiercy** [readthedocs/ext-theme#353] opened 2024-05-16 07:36 UTC
## Details

In the RTD Beta Dashboard at:

https://beta.readthedocs.org/dashboard/volto/edit/

...when I attempt to add a maintainer by their RTD username, I get an `HTTP ERROR 405` message.

When I use the standard Dashboard version at:

https://readthedocs.org/dashboard/volto/users/

...then I am able to add a maintainer by their RTD username.

## Expected Result

In the RTD Beta Dashboard, I should be able to add a maintainer by their RTD username.

## Actual Result

```text
This page isn’t working
If the problem continues, contact the site owner.
HTTP ERROR 405
```

![Screenshot 2024-05-16 at 12 30 39 AM](https://github.com/readthedocs/readthedocs.org/assets/102112/015a78d7-2a22-4c7f-94c1-fbdd9c5034b4)

p.s. -- I love the Beta Dashboard!

**Comment by stsewd** [comment] 2024-06-20 21:04
Hmm, I wasn't able to replicate this. It works on firefox and chrome for me.

**Comment by stevepiercy** [comment] 2024-06-20 21:50
FWIW, I used Chrome at the time.

**Comment by humitos** [comment] 2024-06-21 11:25
I'm not able to reproduce this issue anymore 🤷🏼 . I'm going to close it for now, but feel free to re-open if it still happening to you.

**Closed by humitos** 2024-06-21 11:25 UTC
Labels: Bug, Accepted
